#here you can change the websocket port ps: if you change the websocket port here you need
#to change also on bot discord
websocket:
  port: 8080

messages:
  prefix-discord: "[Discord]"
  prefix-success: "✅"
  prefix-error: "❌"

  format-to-player: "%prefix-discord% [%discordUser% ➜ %minecraftUser%] %message%"
  format-to-discord: "%minecraftUser%|%discordUser%|%message%"

  error-player-not-found: "%prefix-error% Il giocatore '%player%' non è online."
  error-bad-format: "%prefix-error% Formato errato. Usa: discordUser|minecraftUser|messaggio"
  error-no-discord-connected: "%prefix-error% Nessun bot Discord connesso."

  success-message-sent: "%prefix-success% Messaggio inviato a %player%"
  success-discord-message-sent: "%prefix-success% Messaggio inviato a Discord user %discordUser%"
